dataset:
  name: codex-m
  num_entities: 17050
  num_relations: 51
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
import:
- transe
- reciprocal_relations_model
lookup_embedder:
  dim: 256
  initialize: xavier_uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.01903646088689759
    uniform_:
      a: -0.652908295305511
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 1
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    o: 16
    s: 402
reciprocal_relations_model:
  base_model:
    type: transe
train:
  auto_correct: true
  batch_size: 512
  loss: margin_ranking
  loss_arg: 2.335715088993311
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 6
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.003722483096197307
  type: negative_sampling
transe:
  entity_embedder:
    dropout: 0.46394078247249126
    normalize:
      p: -1.0
    regularize_weight: 6.227687287890245e-06
  l_norm: 2.0
  relation_embedder:
    dropout: 0.04913484863936901
    normalize:
      p: -1.0
    regularize_weight: 3.5193161276337565e-06
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05

